### ISSUE TITLE
Add flag to clientError to indicate if the user was shown an alert

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-core#12]
We are now tracking client errors and potentially emailing or otherwise broadcasting them with more visibility. However it's not currently clear from the errors themselves whether the user was shown a modal exception dialog and forced to interact with it, vs. having an error tracked due to a background failure (e.g. bg refresh timeout).

Would be helpful to distinguish between the two if we could via an additional flag - `userAlertShown` (or something a bit better).

**Comment by cnrudd** [comment]
userShownAlert ?

**Comment by lbwexler** [comment]
👍

**Comment by cnrudd** [comment]
This issue is about to be merged into the main branches.

Apps that take this change in an environment in which their hibernate dbCreate setting is set to 'update' have nothing to do to take this change.

If the app environment is production, or for some other reason the dbCreate setting is one that doesn't allow hibernate to make updates to the app database, developers must run this SQL on the app DB before taking this change:

* MS SQL SERVER*
```
ALTER TABLE xh_client_error ADD userAlerted tinyint DEFAULT 0 NOT NULL
```
