### ISSUE TITLE
Hoist needs built-in proxy support

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-core#49]

**Comment by cnrudd** [comment]
I found that hoist core already has a proxy service:  https://github.com/exhi/hoist-core/blob/develop/grails-app/services/io/xh/hoist/http/BaseProxyService.groovy

I've made a small change to a customer's httpClient so that the client can be used by this existing ProxyService.   PR is submitted on customer's hoist repo, with Lee and Anselm added as reviewers.

**Comment by cnrudd** [comment]
I think this is going to require a minor change to 
https://github.com/exhi/hoist-dev-utils/blob/master/configureWebpack.js#L72 .
```javascript
baseUrl = env.baseUrl || (prodBuild ? '/api/' : `http://${devHost}:${devGrailsPort}/`),
```
and/or
https://github.com/exhi/hoist-core/blob/develop/grails-app/controllers/io/xh/hoist/UrlMappings.groovy#L37
```java
"/proxy/$name/$url**"{controller = 'proxyImpl'}
```

and/or
https://github.com/exhi/hoist-react/blob/develop/svc/FetchService.js#L52
```javascript
if (!url.startsWith('/') && !url.includes('//')) {
            url = XH.baseUrl + url;
        }
```

Maybe we should create an env.proxyUrl property in configureWebpack.js that would do:
```javascript
proxyUrl = env.proxyUrl || (prodBuild ? '/' : `http://${devHost}:${devGrailsPort}/`),
```
and change this
https://github.com/exhi/hoist-react/blob/develop/svc/FetchService.js#L52
```javascript
if (!url.startsWith('/') && !url.includes('//')) {
            url = XH.baseUrl + url;
        }
```

to 

```javascript
if (url.startsWith('proxy/') {
            url = XH.proxyUrl + url;
} else if (!url.startsWith('/') && !url.includes('//')) {
            url = XH.baseUrl + url;
        }
```


Let me know if you agree.  The currrent logic in fetch and configureWebpack.js works for development env, but I don't think it will work in production since the URL will become /api/proxy/....  which doesn't match the grails urlmapping.

**Comment by lbwexler** [comment]
Can we close this ticket now colin?

**Comment by cnrudd** [comment]
Yes, Hoist has a proxy:  https://github.com/exhi/hoist-core/blob/develop/grails-app/services/io/xh/hoist/http/BaseProxyService.groovy.  

No changes to Hoist were needed to be able to use the proxy in a client's apps.
